disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - file_name_no_space
  - first_where
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_random
  - let_var_whitespace
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - strict_fileprivate
  - switch_case_alignment
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

excluded:
  - Pods
  - Carthage
  - .build

line_length: 120
function_body_length: 100
type_body_length: 400
file_length: 1000

force_cast: warning
force_try: warning
force_unwrapping: error
implicitly_unwrapped_optional: error

deployment_target:
  iOS: 17.0
